- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Pacman
      become: true
      pacman:
        update_cache: yes
        state: present
      tags:
        - install
        - core
  tasks: 
    - include_vars: 
        file: ./tasks/packages
#    - include_tasks: tasks/ssh.yaml
    - include_tasks: tasks/package-dependencies.yaml
    - include_tasks: tasks/package-install.yaml
#    - include_tasks: tasks/git-setup.yaml
#    - include_tasks: tasks/dotfiles.yaml

    # docker playbook not running - investigate later.
    # in the meantime run - https://docs.docker.com/engine/install/linux-postinstall/
    # - include: playbook/docker.yaml

