- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Pacman
      become: true
      pacman:
        update_cache: yes
        state: present
      tags:
        - install
        - core
  tasks: 
    - include_vars: 
        file: ./tasks/service-packages
    - include_tasks: tasks/ssh.yaml
    - include_tasks: tasks/package-dependencies.yaml
    - include_tasks: tasks/package-install.yaml
    - include_tasks: tasks/rust.yaml
    - include_tasks: tasks/git-setup.yaml
    - include_tasks: tasks/dotfiles.yaml
    - include_tasks: tasks/security.yaml
    - include_tasks: tasks/service-enable.yaml
    - include_tasks: tasks/docker.yaml

