---
- name: Clone yay-git from AUR and install it
  become: true 

  tasks:
    - name: Create a temporary directory
      ansible.builtin.file:
        path: /tmp/yay
        state: directory
      become: true

    - name: Clone yay-git from AUR
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay-git.git
        dest: /tmp/yay
      become: true

    - name: Build and install yay-git
      ansible.builtin.command:
        cmd: chdir=/tmp/yay makepkg -si
      become: true

