- name: Install System Packages 1
  become: true
  pacman:
    name: ["git", "base-devel", "cmake", "pkgconf"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2
  become: true
  pacman:
    name: 
      - "lua"
      - "unzip"
      - "libtool"
      - "gettext"
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3
  become: true
  pacman:
    name: 
      - "curl"
      - "htop"
      - "ccache"  
      - "tree"
      - "go"
      - "lsof"
      - "ninja"
      - "python-pip"
      - "moreutils"
      - "clang"
      - "zsh"
      - "neofetch"
  tags:
    - install
    - core

- name: Install System Packages 4
  become: true
  pacman:
    name: 
      - "ttf-font-awesome"
      - "ttf-droid"
      - "ttf-ubuntu-font-family"
      - "ttf-nerd-fonts-victor-mono"
      - "nerd-fonts"
      - "pacman-contrib"
  tags:
    - install
    - core
    - arch
      
- name: Install System Packages 5 
  become: true
  pacman:
    name: 
      - "pulseaudio-alsa"
      - "pulseaudio-bluetooth"
      - "pulseaudio-equalizer"
      - "pulseaudio-jack"
      - "alsa-utils"
      - "playerctl"
      - "dunst"
      - "bluetoothctl"
  tags:
    - install
    - core
    - arch

- name: Install System Packages 6 sway specific packages 
  become: true
  pacman:
    name: 
      - "wofi"
      - "waybar"
  tags:
    - install
    - core
    - arch

- name: Install Docker
  become: true
  pacman:
    name: ["docker-compose", "docker"] 
  tags:
    - install 
