- name: Start Docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: Create Docker group
  group:
    name: docker
    state: present
  tags:
    - docker

- name: Add user to Docker group
  command: usermod -aG docker "{{ lookup('pipe', 'whoami') }}"
  become: true
  tags:
    - docker

- name: Switch to the Docker group
  command: newgrp docker
  become_user: "{{ lookup('pipe', 'whoami') }}"
  tags:
    - docker

