- hosts: localhost
#  vars:
#    source_key: "./.ssh/id_rsa"
#    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
#    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - name: Update Pacman
      become: true
      pacman:
        update_cache: yes
      tags:
        - install
        - core

    - name: Include playbook/productivity.yaml
      include_tasks: playbook/productivity.yaml

    - name: Include playbook/core.yaml
      include_tasks: playbook/core.yaml
