
- name: Create a temporary directory
  ansible.builtin.file:
    path: /tmp/yay
    state: directory
  become: true

- name: Clone yay-git from AUR
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-git.git
    dest: /tmp/yay
  become: true

- name: Ensure write permissions for the directory
  ansible.builtin.file:
    path: /tmp/yay
    state: directory
    mode: '0777'
  become: true

- name: Build and install yay-git
  ansible.builtin.command:
    cmd: makepkg -si --noconfirm
    chdir: /tmp/yay
  become: false

   
