- name: Install Productivity Packages
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ productivity }}"
  tags:
    - install
    - core

- name: Install Utilities Packages
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ utilities }}"
  tags:
    - install
    - core 

- name: Install Development Packages
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ development }}"
  tags:
    - install
    - core 

      
- name: Install AUR Packages
  become: false 
  command: yay -S {{ item }} --noconfirm
  loop: "{{ aur_packages }}"
  tags:
    - install
    - core 



