- name: kdenlive repository (Arch Linux)
  become: true
  pacman:
    name: kdenlive
    update_cache: true
  tags:
    - install
    - productivity

- name: shutter repository (Arch Linux)
  become: true
  pacman:
    name: shutter
    update_cache: true
  tags:
    - install
    - productivity

- name: Install packages including kdenlive and shutter
  become: true
  pacman:
    name: 
      - "tmux"
      - "brightnessctl"  
      - "fzf"
      - "gimp"
      - "xclip"
      - "kdenlive"
      - "screenkey"
      - "tldr"
      - "wget"
      - "xclip"
      - "curl"
      - "tree"
      - "ripgrep"
      - "shutter"
      - "telegram-desktop"
  tags:
    - install
    - productivity

