- name: Update package cache
  pacman:
    update_cache: yes

- name: Install kdenlive
  become: true
  pacman:
    name: "kdenlive"
    update_cache: true
  tags:
    - install
    - productivity

- name: Install shutter
  become: true
  pacman:
    name: "shutter"
    update_cache: true
  tags:
    - install
    - productivity

- name: Install packages
  become: true
  pacman:
    name: 
      - "tmux"
      - "alacritty"
      - "stow"
      - "fzf"
      - "gimp"
      - "xclip"
      - "kdenlive"
      - "screenkey"
      - "tldr"
      - "wget"
      - "xclip"
      - "curl"
      - "tree"
      - "ripgrep"
      - "shutter"
      - "telegram-desktop"
  tags:
    - install
    - productivity

