- name: Update package cache
  pacman:
    update_cache: yes

- name: Clone Yay repository
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
    version: master

- name: Build and install Yay
  command: chdir=/tmp/yay makepkg -si

- name: Install AUR packages
  yay:
    name:
      - "autotiling"
    state: present

- name: kdenlive repository (Arch Linux)
  become: true
  pacman:
    name: kdenlive
    update_cache: true
  tags:
    - install
    - productivity

- name: shutter repository (Arch Linux)
  become: true
  pacman:
    name: shutter
    update_cache: true
  tags:
    - install
    - productivity

- name: Install packages including kdenlive and shutter
  become: true
  pacman:
    name: 
      - "tmux"
      - "alacritty"
      - "stow"
      - "fzf"
      - "gimp"
      - "xclip"
      - "kdenlive"
      - "screenkey"
      - "tldr"
      - "wget"
      - "xclip"
      - "curl"
      - "tree"
      - "ripgrep"
      - "shutter"
      - "telegram-desktop"
  tags:
    - install
    - productivity

