- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Transfer encrypted SSH private key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Decrypt SSH private key
  ansible.builtin.expect:
    command: "ansible-vault decrypt {{ dest_key }}"
    responses:
      "Enter Vault password": "{{ vault_password }}"
  when: "'vault' in dest_key" 
  tags:
    - decrypt
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh


