---
- name: Configure Docker group and add user to it
  hosts: your_target_hosts
  become: yes
  tasks:
    - name: Start Docker service
      become: true
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Switch to the Docker group
      command: newgrp docker
      become_user: "{{ ansible_user }}"

